In [1]:
IniList = [1,"satu",1.5,"satu koma lima",2]
print(IniList)

[1, 'satu', 1.5, 'satu koma lima', 2]


In [3]:
type(IniList)

list

In [5]:
# Menggunakan Constructor
IniList2 = list((1, 2, 3, 4, 5, 'a', 'b', 'c', 'd'))
print(IniList2)
# menggunakan looping
IniList = [i for i in range(0, 10)]
print(IniList)
IniList = [i for i in "apakabar kalian semua"]
print(IniList)
# ditambahkan if 
IniList = [i for i in range(0, 10) if i % 2 == 0]
print(IniList)

[1, 2, 3, 4, 5, 'a', 'b', 'c', 'd']
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
['a', 'p', 'a', 'k', 'a', 'b', 'a', 'r', ' ', 'k', 'a', 'l', 'i', 'a', 'n', ' ', 's', 'e', 'm', 'u', 'a']
[0, 2, 4, 6, 8]


In [6]:
arrInt = [0, 1, 2, 3, 4, 5, 6, 7, 8, 10]

print(arrInt[::]) # mengakses setiap elemen dalam list
print(arrInt[1:5]) # mengakses setiap elemen dari index 1 hingga index 5
print(arrInt[2:9:3]) # mengakses mulai dari index 2 hingga index 9 dengan lompatan 3 index

[0, 1, 2, 3, 4, 5, 6, 7, 8, 10]
[1, 2, 3, 4]
[2, 5, 8]


In [9]:
IniList = ['a', 'b', 'c', 'd', '1', '2', '3']

for i in IniList: # berdasarkan elemen list
    print(i, end=", ")

for i in range(len(IniList)): # berdasarkan index
    print(IniList[i])

a, b, c, d, 1, 2, 3, a
b
c
d
1
2
3


In [11]:
IniList = [[1, 2], ['a', 'b'], [3, [4, 5]]]
print(IniList[0][0])
print(IniList[1][0])
print(IniList[2][0])
print(IniList[2][1])

1
a
3
[4, 5]


In [12]:
iniLIST = [1, 2, 3, 4]
print(iniLIST)

[1, 2, 3, 4]


In [14]:
iniLIST.pop()
print(iniLIST)

[1, 2, 3]


In [15]:
import numpy as np

In [17]:
arrFloat = np.array([10, 3, 7, 8, 90]) # secara default menjadi int
arrInt = np.array([1, 4, 3, 20, 11], int) # array dengan tipe data integer
arrStr = np.array(['Cristiano', 'Mbappe', 'Modric', 'Griezmann'])
arr2D = np.array([[1, 2, 3],
		  [4, 5, 6],
		  [7, 8, 9]])
arr3D = np.array([[[1, 2, 3],
		   [4, 5, 6],
		   [7, 8, 9]],
		  [[10, 11, 12],
	           [13, 14, 15],
	           [16, 17, 18]]], float)

print(arrFloat)
print(arrInt)
print(arrStr)
print(arr2D)
print(arr3D)

[10  3  7  8 90]
[ 1  4  3 20 11]
['Cristiano' 'Mbappe' 'Modric' 'Griezmann']
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[[ 1.  2.  3.]
  [ 4.  5.  6.]
  [ 7.  8.  9.]]

 [[10. 11. 12.]
  [13. 14. 15.]
  [16. 17. 18.]]]


In [19]:
my_set = {1, 2, 3, 4, 5, 4, 5, 7}
print(my_set)

{1, 2, 3, 4, 5, 7}


In [21]:
my_set = {1, 2, 3, 4, 5}
my_set.add(6)
print(my_set)

my_set.update([6, 7, 8])
print(my_set)

my_set.remove(3)
print(my_set)

my_set1 = {1, 2, 3}
my_set2 = {3, 4, 5, 2}
my_set3 = my_set1.union(my_set2)
print(my_set3)
T

{1, 2, 3, 4, 5, 6}
{1, 2, 3, 4, 5, 6, 7, 8}
{1, 2, 4, 5, 6, 7, 8}
{1, 2, 3, 4, 5}


In [22]:
my_tuple = (5, 2, 8, 1, 3)
sorted_tuple = sorted(my_tuple)
print(sorted_tuple)

[1, 2, 3, 5, 8]


In [23]:
# Mendeklarasikan sebuah dictionary
person = {"name": "John", "age": 30, "city": "New York","name" : "FAISAL"}
# Menghapus semua pasangan key-value pada dictionary
print(person) 


{'name': 'FAISAL', 'age': 30, 'city': 'New York'}


In [24]:
person = {"name": "John", "age": 30, "city": "New York"}
# Mengembalikan daftar pasangan key-value dalam bentuk tuple
print(person.items())  

dict_items([('name', 'John'), ('age', 30), ('city', 'New York')])


In [26]:
def mean(n):
    sum = 0
    for i in range(len(n)):
        sum = sum + int(n[i])
    return round(sum/len(n), 2)

def median(n):
    myList = [int(i) for i in n]
    myList.sort()
    return myList[int(len(n)/2)]

def modus(n):
    myDict = {}
    for i in n:
        if i not in myDict.keys():
            myDict[i] = n.count(i)
    print(myDict)
    result = []
    for key, value in myDict.items():
        if value == max(myDict.values()):
            result.append(key)
    return result

N = input()
meanResult = mean(N)
medianResult = median(N)
modusResult = modus(N)
print(f"Mean: {meanResult}")
print(f"Median: {medianResult}")
print(f"Modus: {' '.join(modusResult)}")


 0895365037183


{'0': 2, '8': 2, '9': 1, '5': 2, '3': 3, '6': 1, '7': 1, '1': 1}
Mean: 4.46
Median: 5
Modus: 3
